export const ERROR_CONFIG = {
  AUTH: {
    NEED_EMAIL: "AUTH_NEED_EMAIL",
    USER_EXIST: "AUTH_USER_EXIST",
    USER_NOT_EXIST: "AUTH_USER_NOT_EXIST",
  },
  PASSWORD: {
    SAME_AS_OLD: "PASSWORD_SAME_AS_OLD",
  },
};
