export const SHOPLAZZA_SCOPES = [
  "read_product write_product",
  "read_collection",
  "write_collection",
  "read_script_tags",
  "write_script_tags",
  "read_app_proxy",
  "write_app_proxy",
  "read_data",
  "write_data",
  "read_shop",
  "read_comments",
  "write_comments",
  "read_shop_navigation",
  "write_shop_navigation",
  "read_search_api",
  "write_search_api",
  "read_themes",
  "unauthenticated_read_checkouts",
  "unauthenticated_write_checkouts",
  "unauthenticated_read_customers",
  "unauthenticated_write_customers",
  "unauthenticated_read_customer_tags",
  "unauthenticated_read_content",
  "unauthenticated_read_product_listings",
  "unauthenticated_read_product_tags",
  "unauthenticated_read_selling_plans",
];
